### ISSUE TITLE
Tracking of heuristic evaluations

### ISSUE THREAD

**Issue by thomasgohard** [wet-boew/wet-boew-styleguide#18]
Check a component once a minimum of three independent evaluations have been performed.

**Note:** (M) indicates that the interface is dependant on the core device or platform components (ex. keyboards, dropdown rendering etc). These components may require additional testing on platforms such as iOS, Android, Blackberry.
## Priority components
- [x] [Tabbed Interface](https://github.com/wet-boew/wet-boew-styleguide/issues/21)
- [x] [Tabbed Interface with slide-horz](https://github.com/wet-boew/wet-boew-styleguide/issues/37) 
- [x] [Expand/collapse](https://github.com/wet-boew/wet-boew-styleguide/issues/3)
- [x] [Archiving content](https://github.com/wet-boew/wet-boew-styleguide/issues/4)
- [x] [Footnotes](https://github.com/wet-boew/wet-boew-styleguide/issues/5) 
- [x] [Auto-complete](https://github.com/wet-boew/wet-boew-styleguide/issues/6) (M)
- [x] [Lightbox](https://github.com/wet-boew/wet-boew-styleguide/issues/7)
- [x] [Form validation](https://github.com/wet-boew/wet-boew-styleguide/issues/8)
- [x] [Dialogue box](https://github.com/wet-boew/wet-boew-styleguide/issues/9)
- [x] [Share widget](https://github.com/wet-boew/wet-boew-styleguide/issues/10) 
- [x] [Multimedia player](https://github.com/wet-boew/wet-boew-styleguide/issues/11) (M)
- [x] [Table enhancement (Filterable/data)](https://github.com/wet-boew/wet-boew-styleguide/issues/12) (M)
- [x] [Carousel](https://github.com/wet-boew/wet-boew-styleguide/issues/13)
- [x] [Twitter embedded timeline](https://github.com/wet-boew/wet-boew-styleguide/issues/14)
- [x] [Pagination](https://github.com/wet-boew/wet-boew-styleguide/issues/24)
- [x] [Main menu (Large views)](https://github.com/wet-boew/wet-boew-styleguide/issues/15)
- [x] [Small & medium view fly-out menu (Megamenu equivalent)](https://github.com/wet-boew/wet-boew-styleguide/issues/20)
- [x] [Search results](https://github.com/wet-boew/wet-boew-styleguide/issues/33) 
- [x] [Badges](https://github.com/wet-boew/wet-boew-styleguide/issues/23)
- [x] [Breadcrumbs](https://github.com/wet-boew/wet-boew-styleguide/issues/34)
- [x] [Links](https://github.com/wet-boew/wet-boew-styleguide/issues/25)
- [x] [Buttons](https://github.com/wet-boew/wet-boew-styleguide/issues/26)
- [x] [Language selector](https://github.com/wet-boew/wet-boew-styleguide/issues/35)
- [x] [Mandatory fields](https://github.com/wet-boew/wet-boew-styleguide/issues/28) (M)
- [x] [Message boxes/alerts](https://github.com/wet-boew/wet-boew-styleguide/issues/30) 
- [x] [Calendar: Date picker](https://github.com/wet-boew/wet-boew-styleguide/issues/17) (M)
- [x] [Short forms](https://github.com/wet-boew/wet-boew-styleguide/issues/29) (M)
- [x] [Feedback/Rate this page](https://github.com/wet-boew/wet-boew-styleguide/issues/16) (M) 
- [x] [Images](https://github.com/wet-boew/wet-boew-styleguide/issues/27)
- [x] [Table of contents (within page links)](https://github.com/wet-boew/wet-boew-styleguide/issues/36)
- [x] [Panels](https://github.com/wet-boew/wet-boew-styleguide/issues/31)
- [x] [Pills](https://github.com/wet-boew/wet-boew-styleguide/issues/45)
- [x] [Labels](https://github.com/wet-boew/wet-boew-styleguide/issues/46) 
## Other components
- [ ] Contextual links
- [ ] Data Inview
- [ ] Long form navigation (generic, wizard, accordion ...etc)
- [ ] International phone numbers
- [ ] Thermometer
- [ ] Q&As
- [ ] Calendar: Events calendar 
- [ ] Charts and graphs
- [ ] Mathematical/scientific formula display
- [ ] Meter 
- [ ] Log-in/Sign-in
- [ ] Persistent storage
- [ ] Progress bar
- [ ] Session timeout
- [ ] Slider control
- [ ] Text highlighting
- [ ] Toggle
- [ ] Tooltip
- [ ] Web feeds
- [ ] Zebra striping
- [ ] Slide out tab
- [ ] Geomap
